### ISSUE TITLE
CORS issue on saving a new calendar event

### ISSUE THREAD

**Issue by omeryousaf** [omeryousaf/alumni_network_ui#10]
**Current**
The api call to save a new calendar event does not reach backend, rather it is blocked/killed by the browser by marking it as  cross origin.

**Expected**
Save calendar event api call should work without CORS error.

**Comment by Shapokhan** [comment]
This issue belongs to the backend and resolve [here](https://github.com/omeryousaf/alumni_network_api/issues/4)
