### ISSUE TITLE
User should be navigated on hitting all routes & Cross Origin requests rejected by API Server

### ISSUE THREAD

**Issue by Alihaider168** [omeryousaf/alumni_network_ui#6]
## Problem
1. Currently, hitting any route like `http://localhost:8000/login`, or `http://localhost:8000/directory` etc. results in **404** error (see attached snapshot below) **but only `http://localhost:8000/` works**.
![routingerror](https://user-images.githubusercontent.com/29670845/65147784-4c060f00-da38-11e9-981c-0801c3e02dca.PNG)
2. API server (based on https://github.com/omeryousaf/alumni_network_api) treats requests from the separate frontend (this repo) as cross origin and causes issues like https://github.com/omeryousaf/alumni_network_api/issues/3.

## Acceptance Criteria
1. Any route with correct domain (where the frontend server is live e.g. `http://localhost:8000`) should return with main index.html (which then loads the whole app).
2. Resolve https://github.com/omeryousaf/alumni_network_api/issues/3.

**Comment by omeryousaf** [comment]
Fixed by https://github.com/omeryousaf/alumni_network_ui/pull/8.
